name: libhoney_dart
version: 0.1.0
description: A Dart implementation of Honeycomb client library (or Libhoney) for Honeycomb.io

environment:
  sdk: '>=2.12.0 <3.0.0'

homepage: https://github.com/One-Nub/libhoney-dart
repository: https://github.com/One-Nub/libhoney-dart

dependencies:
  http: ^0.13.3